name: Development environment for "add-widget" branch 

on:
  push:
    branches: [ "add-widget" ]
  pull_request:
    branches: [ "add-widget" ]

jobs:
  build:
    runs-on: ubuntu-latest
    with:
      stage: dev
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    # - run: npm run build --if-present
    # - run: npm test